import {
  doc,
  setDoc,
  collection,
  getDocs,
  updateDoc,
  deleteDoc,
} from "firebase/firestore/lite";
import { db } from "./config"; // Import your Firebase app configuration

// Define a type for the product
interface Product {
  id?: string; // Optional because it will be auto-generated by Firestore
  name: string;
  price: number;
  description?: string; // Optional field
  // Add other fields as needed
}

// Function to add a product
export const addProduct = async (product: Omit<Product, "id">) => {
  try {
    // Generate an auto-ID document
    const newDocRef = doc(collection(db, "products"));

    // Add the product data
    await setDoc(newDocRef, product);

    console.log("Product added successfully with ID:", newDocRef.id);
  } catch (error) {
    console.error("Error adding product: ", error);
  }
};

// Fetch all products
export const fetchProducts = async (): Promise<Product[]> => {
  try {
    const snapshot = await getDocs(collection(db, "products"));
    const products = snapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    })) as Product[];
    return products;
  } catch (error) {
    console.error("Error fetching products:", error);
    return [];
  }
};

// Update a product
export const updateProduct = async (
  productId: string,
  updatedData: Partial<Product> // Use Partial to allow updating only specific fields
) => {
  try {
    const productRef = doc(db, "products", productId);
    await updateDoc(productRef, updatedData);
    console.log("Product updated successfully");
  } catch (error) {
    console.error("Error updating product:", error);
  }
};

// Delete a product
export const deleteProduct = async (productId: string) => {
  try {
    const productRef = doc(db, "products", productId);
    await deleteDoc(productRef);
    console.log("Product deleted successfully");
  } catch (error) {
    console.error("Error deleting product:", error);
  }
};
